defaults:
  services:
    max-memory: 1gb
override:
  services:
    accounting-v3:
      max-memory: 512mb
    logstash:
      max-memory: 2gb
    rollunnet-php:
      max-memory: 4gb
    mws-inv-php:
      max-memory: 2gb
